### ISSUE TITLE
Constant server crashes

### ISSUE THREAD

**Issue by sunotoif** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#20]
When started, the server boots up and functions normally. Once a player joins the server, there is a delay of functionality, then the server goes into a phase of crashes and unresponsiveness. The control panel does not register that there are players on the server or there are is any CPU usage. The web console does not register any commands inputed but still records logs. The only addons installed are: ULX, ULIB, DarkRPmodification and the DarkRP gamemode. MySQLoo and TMySQL V4 are not installed.

Server switches between ports as well.

Edit 1: Server crashes after boot up even if no players join.
![b2df8e9b87c8d19f81a2111d4b01d238](https://user-images.githubusercontent.com/15991434/36349493-25b4f838-143d-11e8-89b8-858e2838e028.png)
![8ba99342ba24714d3d0678d20098e07d](https://user-images.githubusercontent.com/15991434/36349504-5555a5ce-143d-11e8-9800-7fccb10d6409.png)

**Comment by ertug2** [comment]
Thank you for contacting us.  Could you contact us directly with your server IP:Port so that we can look deeper into it? The PID that you had is long gone in our system since the server was restarted.

The control panel waits three minutes after your server starts to try to check if the server is online and also to check for your server name/player count. If the server fails to query at that point, then it is put into "not responding mode." If the web console does not record any input after you enter it (if the server fully booted up) then the server most likely already crashed which would line up with the "not responding" status. It's very unlikely for the server to just randomly crash with only those set of server add-ons without anything else unless you were missing the map or vice versa. Without knowing your serverIP:Port or server ID, I cannot find your crash logs to see exactly what was going on directly.

**Comment by sunotoif** [comment]
Sure thing, the server IP:Port is : 208.103.169.44:27025 (208.103.169.44_27025) 

I saw that you have went online to check on the server, I'm unsure if you have fixed it by now.

**Comment by ertug2** [comment]
It appeared to be fine when I joined it earlier. I would say if you end up having any more problems then respond back to that ticket. This page is more for panel related issues and not for specific node related issues as you were experiencing earlier with the steam authentication bug.
