### ISSUE TITLE
The Workshop Downloader Start Button is Broken

### ISSUE THREAD

**Issue by PopeFrancis112** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#7]
After I Paste in my URL for my Steam Collection, and I click Start Workshop Download, It just sits there. I am using a sub acct. But the owner stated i have full access privileges. This happened on 7/31/2017 at 08:46 AM

**Comment by ertug2** [comment]
That sounds specifically like an isolated issue and not something that wouldn't directly be related to our control panel either missing a feature or experiencing a bug. Could you send us a picture of what you put into the fields along with what you ticked? It's also better if you open a support ticket directly on our site regarding it since this is more of an isolated situation.
