### ISSUE TITLE
Enhancement - Console window

### ISSUE THREAD

**Issue by pumab** [gmc-hosting/gmcpanel-bug-reports-and-suggestions#8]
I really like the user friendly enviroment , but it would be really nice if the Web Console window could be enlarged / resized , its very thin. Hard to see long errors , Also a Pause button would be really nice next to the Auto Scroll function. Thanks :) 

ps. more history ? So I can scroll up more ?

**Comment by ertug2** [comment]
I do thank you for contacting us. The web console can currently be resized to a full-screen mode only. I don't personally see much use specifically for people to be able to resize it under full-screen mode only because usually put it on their other monitors to look over the logs. 

A pause idea is not too bad of an idea. I'll look into that. As for having more text show up, the issue is that some browsers or mobile devices have only a finite amount of RAM. Once you start showing up too much data or constantly loading more data it starts the lag the browser and or mobile device until the point where it just crashes. For that reason, we've limited it to a limit that is more of a middleman for every device.

Let me know if you have any other suggestions. Thanks.

**Comment by pumab** [comment]
I see, thanks for the reply maybe u can add a setting where we can set the history ammount. So users who crash because of it can reduce it ?

**Comment by TaliXor** [comment]
I'd like to add onto this suggestion.

Personally, I really dislike the web console you guys provide. While I get that showing too much information might cause some devices/browsers to crash or something, I think you should at least add an option to be able to switch to a "**developer web console**" that doesn't cut off any of the logs from console whatsoever.

There are so many times that I'm trying to put something on the server and see what the issue with the addon is by looking at console, but the error has already been cut off. This issue has forced me to go to another host for a development server that doesn't have a console that cuts off parts of the console after a certain amount of text. For example: Serenity servers has a console that shows every single detail from console and cuts off nothing.

I think this feature would be extremely useful for developers such as myself, while at the same time including the same web console by default.

**Comment by ertug2** [comment]
What I'll do is make it so that the system filters 1024 lines from the file instead of 150. TCAdmin which is what our competitors rely on also has a limit on how much it shows. Even desktop browsers experience stability issues when loading too much. Do you believe that the new limit would be good enough? Making it show the entire file is a terrible idea especially if the file is multiple megabytes in size if not more.

If so I'll push that update within a week or so. Right now we're adapting Rust to our control panel.

**Comment by ertug2** [comment]
I have also added a pause feature since it was a great idea. Here is a preview of that: 

![image](https://user-images.githubusercontent.com/7322155/33519715-9537ec1a-d77a-11e7-9b0f-8919b175de1f.png)

I didn't adopt the console resize feature since there is a full-screen option to fit the web console onto the entire screen. Let me know if you have any other recommendations or enhancements. Thanks.

**Comment by TaliXor** [comment]
I would absolutely love a 1024 line limit. A much better improvement than 150.

**Comment by ertug2** [comment]
I have pushed both changes now. Feel free to reopen this or make a new bug report if anything else comes up pertaining to the web console.
